### ISSUE TITLE
Add (relative) bulding heights

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/bag3d#23]
Currently we only report the absolute height of the top of a building. For many applications it is more interesting to know the height of the building (top - ground). This could eventually replace the ground or roof absolute heights.

**Comment by evetion** [comment]
This would require more research. Experimenting with `roof-50` - `ground-50` will result in several buildings with negative heights and ignores towers on a larger, lower bases. Is this the `multi-level` issue in #13?

**Comment by balazsdukai** [comment]
@evetion no, this is not related to the `multi-level` issue, because the `multi-level` attribute would indicate if the roof geometry contains multiple height levels.

As you say, `roof-50` - `ground-50` easily results in negative heights, the reason for that is a bit convoluted to explain, but has to do with how many points are measured on the walls of the "real" building.

Nevertheless, the relative height would be determined by `roof-X` - `mean ground`, or even `mean roof` - `mean ground`. Thus possibly reporting only a single relative height value per building, and not 6.

**Comment by balazsdukai** [comment]
Repo closes because it has been superseded.
