### ISSUE TITLE
Consolidate height_valid attribute

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/bag3d#28]
Currently, `height_valid is TRUE when bouwjaar > 0 OR bouwjaar > ahn_date OR nr_roof_pts > 0`
The documentation and the quality table only reports `bouwjaar > ahn_date`.

**Comment by evetion** [comment]
Also, the `height_valid` column only has `TRUE` values. I would expect `FALSE` values as well, instead of the empty fields now.

**Comment by balazsdukai** [comment]
Which data format did you use?

**Comment by evetion** [comment]
The Geopackage one @ http://3dbag.bk.tudelft.nl/data/gpkg/bag3d_2019-09-28.gpkg

**Comment by balazsdukai** [comment]
Repo closes because it has been superseded.
