### ISSUE TITLE
Is it possible to create multiple roof types, or detect complex roof shapes using 3Dbag data?

### ISSUE THREAD

**Issue by sebmooreaz** [tudelft3d/bag3d#34]
What I mean is that it's ok to generate buildings with flat or non flat roofs (simple roof shape) using a mean height.

But what about if the roof type is gable and other types, what do you think would be the best way to do that? What I mean essentially is how to generate a 3d model as close to reality as possible?

Greetings!

**Comment by balazsdukai** [comment]
That's a research field on its own :-) . This bag3d tool itself doesn't do any 3d reconstruction, but manages the instructions for running [3dfier](https://github.com/tudelft3d/3dfier). If you have an executable that can create more complex roof types, then its possible to replace 3dfier. However if the requirements/input of such an executable are very different from 3dfier's, then you'll likely end up building a new software.

**Comment by sebmooreaz** [comment]
Thank you for your reply. That's what I'm figuring out. Did you see the new Microsoft flight simulator technology? Seems quiet interesting..

**Comment by sebmooreaz** [comment]
I can't tell much about what I'm doing but I can say that the 3Dbag services are really good for us. I think that 3dfier does a great job, so there's no point to try to replace it. But thanks to the raw nature of json data there are other purposes possible.

**Comment by sebmooreaz** [comment]
That's the strength of the wfs geoservice from 3dbag, that people can do what they want with the data. it would not be the same with 3dfier.
