### ISSUE TITLE
tree disturbance

### ISSUE THREAD

**Issue by niklasbokeolen** [tudelft3d/bag3d#38]
Hello, 
First of all, thank you for producing such a fantastic dataset.
I was wondering on how tree disturbance is handled when extracting building heights? 
Especially the cases of smaller building footprints that can be located completely under tree-crowns?

I am working on a project were we need to identify green roofs and my original idea was to compare tree heights with building heights to filter out none valid cases. But if the building height is too much influenced by the tree height I might need to adjust this.

Thank you

Best Regards

Niklas Boke Olén
Researcher Lund University, Sweden

**Comment by balazsdukai** [comment]
Hi Niklas, the aerial Lidar point cloud that is used as input has a buildings and trees/vegetation classified separately. For the building reconstruction only the building-points are used and the vegetation is ignored.
Now all this said, there is some level of misclassification for sure, but unfortunately I cannot tell you how much. To be honest I never checked buildings with green roofs in the data, esp. not the case that you mention, so I don't know how would that work.
I hope this helps somewhat. If it answers your question, please close the issue.

**Comment by niklasbokeolen** [comment]
Thanks for your response. I ended up using a different method to get the green roofs then comparing height differences. I think the risk of miss classification is rather high especially for the smaller "garden" buildings that are standing completely under tree crowns. 
Regards

Niklas
