### ISSUE TITLE
Newer version of GDAL will support BAG 2.0 extract out of the box

### ISSUE THREAD

**Issue by yorickdewid** [tudelft3d/bag3d#39]
The next version GDAL will be able to read BAG 2.0 extract files directly. This would save a few steps in the process and would allow BAG PND datalayer to be read into PostGis at once. LV BAG 2.0 extract files are supported. All datasets (PND,NUM,etcc) are supported as well as reading partial zip files.

See https://github.com/OSGeo/gdal/pull/2503

**Comment by balazsdukai** [comment]
@yorickdewid excellent, thank you for the info!

**Comment by justb4** [comment]
... and NLExtract uses this new LVBAG Driver to generate a PostGIS Dump now using vanilla Stetl.
The first PG dumps have been successfully made.
See [work in progress](https://github.com/nlextract/NLExtract/tree/bagv2/bagv2/etl).

**Comment by balazsdukai** [comment]
Thanks for the update!
Actually, this repo is outdated already and I'm using the LVBAG driver directly, to read the Pand layer, since that's the only that I need.
