### ISSUE TITLE
LOD order

### ISSUE THREAD

**Issue by SebastienTussiau** [tudelft3d/bag3d#42]
Hello,

I noticed that the order of the LODs in the doc is from LOD0 (low details) to LOD4 (high details).
But other softwares like megascans, unity and blender are going from LOD4 (low details) to LOD0 (high details). See Unity documentation:
https://docs.unity3d.com/Manual/LevelOfDetail.html

It should be that everybody use the same order for the LODs, it would be more coherent.

**Comment by balazsdukai** [comment]
Inded, it would be much easier. But what you refer to is LoD for computer graphics, which has a very different meaning to what LoD is in GIS.
