### ISSUE TITLE
Is it possible to change the webservices WMS and WFS from http:// to https://

### ISSUE THREAD

**Issue by deevee123** [tudelft3d/bag3d#43]
We would like to implement the WMS service in a webviewer. We use Heron MC (javascript)

Unfortunately our browser redirects the URL http:// to https://. We end up with a not responsive request like:
**https**://3dbag.bk.tudelft.nl/data/wms?LAYERS=pand3d&FORMAT=image%2Fpng&STYLES=BAG3D%3Apand_h_75&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG%3A28992&BBOX=135108.8,449452.48,135216.32,449560&WIDTH=256&HEIGHT=256

When I change https:// to http:// all goes well.

So, since the service is not served in https;// we do not receive the requested information.

Are there any plans to change the url to https://?

Kind regards and keep up the good work!

**Comment by balazsdukai** [comment]
In short, yes and no :slightly_smiling_face: 
Soon we are releasing the 3D BAG v2, which will have https . We are putting all our efforts into making the release as soon as possible, thus we are not doing anything anymore for the current 3D BAG. So at this point I can only ask you to wait a little bit more.
