### ISSUE TITLE
Failed to open at ArcGIS pro

### ISSUE THREAD

**Issue by yehanwu** [tudelft3d/bag3d#44]
Hi 

The geopackage file I downloaded (http://3dbag.bk.tudelft.nl/data/gpkg/bag3d_2020-05-13.gpkg) can be added in QGIS, but it failed to add in ArcGIS pro (‘Error: Exception from HRESULT: 0x8004152A’). I tried to export it into shapefile in QGIS and load in ArcGIS pro again, the polygons are shown but no attribute table data (‘failed to load data. Error: a column was specified that does not exist’).

Not sure how to solve the problem but it would much be appreciated if you could provide some help!

**Comment by Athelena** [comment]
Hiya, I just tested it and got the same error. But I then converted the shapefile to a layer in a file geodatabase and the attribute table now works. Hopefully that helps you?

**Comment by yehanwu** [comment]
> Hiya, I just tested it and got the same error. But I then converted the shapefile to a layer in a file geodatabase and the attribute table now works. Hopefully that helps you?

Yes it works! Thank you very much!
